version: "3.9"

services:

  api:
    build:
      context: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8080
    ports:
      - "8000:8080"

  worker:
    build:
      context: .
    command: celery -A api.workers.examples worker --loglevel=info

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    network_mode: "host"
