[tool.poetry]
name = "python-template"
version = "0.0.1"
description = "A starting point for python projects"
authors = ["David Bossanyi"]

[tool.poetry.dependencies]
python = "^3.9, <3.10"
fastapi = {extras = ["all"], version = "^0.78.0"}
celery = "^5.2.6"
pydantic = {extras = ["dotenv"], version = "^1.9.1"}
azure-storage-blob = "^12.12.0"
azure-storage-queue = "2.1.0"
tomli = "^2.0.1"
redis = "^4.3.3"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pre-commit = "^2.19.0"
black = "^22.3.0"
isort = "^5.10.1"
flake8 = "^4.0.1"
mypy = "^0.950"
coverage = "^6.3.3"
pytest-cov = "^3.0.0"
pytest-mock = "^3.7.0"
pytest-env = "^0.6.2"
pytest-celery = "^0.0.0"

[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
markers = [
    "integration",
]
env = [
    "LOCAL_CELERY_BROKER_URL=memory://"
]

[tool.black]
line-length = 120

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120

[tool.coverage.run]
omit = ["tests/*"]
