[tool.poetry]
name = "fastapi-celery-example"
version = "0.0.1"
description = "An example FastAPI app using Celery for task queuing."
authors = ["David Bossanyi"]

[tool.poetry.dependencies]
python = "^3.10, <3.11"
fastapi = "^0.90.0"
celery = { version = "5.3.0b1", allow-prereleases = true}
kombu = { version = "5.3.0b2", allow-prereleases = true}
pydantic = {extras = ["dotenv"], version = "^1.10.4"}
azure-storage-blob = "12.14.1"
azure-storage-queue = "12.5.0"
tomli = "^2.0.1"
uvicorn = "^0.20.0"

[tool.poetry.group.test.dependencies]
pytest = "^7.2.1"
httpx = "^0.23.3"
pytest-mock = "^3.10.0"
pytest-celery = "^0.0.0"
pytest-cov = "^4.0.0"
coverage = "^7.1.0"

[tool.poetry.group.lint.dependencies]
pre-commit = "^3.0.4"
black = "^22.12.0"
isort = "^5.12.0"
flake8 = "^6.0.0"
mypy = "^0.991"
deptry = "^0.8.0"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
markers = [
    "integration",
]
filterwarnings = [
    "ignore::DeprecationWarning:celery.*:",
    "ignore::DeprecationWarning:kombu.*:",
]

[tool.black]
line-length = 120

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120

[tool.coverage.run]
omit = ["tests/*"]

[tool.deptry]
ignore_obsolete = ["kombu", "uvicorn"]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
disallow_untyped_defs = true
files = ["api", "tests"]

[tool.bandit]
skips = ["B101"]
