[tool.poetry]
name = "fastapi-celery-example"
version = "0.0.1"
description = "An example FastAPI app using Celery for task queuing."
authors = ["David Bossanyi"]

[tool.poetry.dependencies]
python = "^3.10, <3.11"
fastapi = "^0.85.2"
celery = { version = "5.3.0b1", allow-prereleases = true}
kombu = { version = "5.3.0b2", allow-prereleases = true}
pydantic = {extras = ["dotenv"], version = "^1.10.2"}
azure-storage-blob = "12.14.1"
azure-storage-queue = "12.5.0"
tomli = "^2.0.1"
uvicorn = "^0.19.0"
requests = "^2.28.1"
pandas = "^1.5.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pre-commit = "^2.20.0"
black = "^22.10.0"
isort = "^5.10.1"
flake8 = "^5.0.4"
mypy = "^0.982"
coverage = "^6.5.0"
pytest-cov = "^4.0.0"
pytest-mock = "^3.10.0"
pytest-celery = "^0.0.0"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
markers = [
    "integration",
]

[tool.black]
line-length = 120

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120

[tool.coverage.run]
omit = ["tests/*"]
