[tool.poetry]
name = "fastapi-celery-example"
version = "0.0.1"
description = "An example FastAPI app using Celery for task queuing."
authors = ["David Bossanyi"]

[tool.poetry.dependencies]
python = "^3.10, <3.11"
fastapi = "^0.78.0"
celery = { version = "5.3.0a1", allow-prereleases = true}
pydantic = {extras = ["dotenv"], version = "^1.9.1"}
azure-storage-blob = "12.13.1"
azure-storage-queue = "12.3.0"
tomli = "^2.0.1"
redis = "^4.3.4"
uvicorn = "^0.18.2"
requests = "^2.28.1"
pandas = "^1.4.3"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pre-commit = "^2.20.0"
black = "^22.6.0"
isort = "^5.10.1"
flake8 = "^4.0.1"
mypy = "^0.961"
coverage = "^6.4.1"
pytest-cov = "^3.0.0"
pytest-mock = "^3.8.2"
pytest-celery = "^0.0.0"

[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
markers = [
    "integration",
]

[tool.black]
line-length = 120

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120

[tool.coverage.run]
omit = ["tests/*"]
