name: CI

on:
  workflow_dispatch:
  pull_request: ~
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: actions/cache@v3
        name: Cache Dependencies
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - uses: actions/cache@v3
        name: Cache Pre-Commit
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip wheel
          curl -sSL https://install.python-poetry.org | python -

      - name: Check Lock File
        run: |
          poetry lock --check

      - name: Install Dependencies
        run: |
          poetry install --no-interaction --no-ansi

      - name: Lint
        run: |
          make lint

      - name: Unit Tests
        run: |
          make test-unit

      - name: Integration Tests
        run: |
          make pre-integration
          make test-integration
          make post-integration

  docker:
    name: Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Container Image
        run: |
          docker buildx build .

  dependabot-automerge:
    name: Dependabot Auto Merge
    needs: [test, docker]
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && ( github.head_ref || github.ref_name ) != 'main' }}
    steps:
      - name: Fetch Dependabot Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve Dependabot PR
        run: gh pr review --approve "$PR_URL"
        if: ${{ (steps.metadata.outputs.package-ecosystem == 'pip' && steps.metadata.outputs.update-type != 'version-update:semver-major') || steps.metadata.outputs.package-ecosystem != 'pip' }}
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Dependabot PR
        if: ${{ (steps.metadata.outputs.package-ecosystem == 'pip' && steps.metadata.outputs.update-type != 'version-update:semver-major') || steps.metadata.outputs.package-ecosystem != 'pip' }}
        run: gh pr merge --auto --squash "$PR_URL" || echo "Merge conflict caused failure, waiting for dependabot to rebase"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
