name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - uses: actions/cache@v3
        name: Cache Dependencies
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - uses: actions/cache@v3
        name: Cache Pre-Commit
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip wheel
          curl -sSL https://install.python-poetry.org | python -

      - name: Install Dependencies
        run: |
          poetry install --no-interaction --no-ansi

      - name: Lint
        run: |
          poetry run pre-commit run --all-files

      - name: Test
        run: |
          poetry run pytest --cov=. --cov-fail-under=100 tests/
