name: CI

on:
  workflow_dispatch:
  pull_request: ~
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    outputs:
      coverage: ${{ steps.coverage.outputs.COVERAGE }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: actions/cache@v4
        name: Cache Dependencies
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - uses: actions/cache@v4
        name: Cache Pre-Commit
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip wheel
          curl -sSL https://install.python-poetry.org | python -

      - name: Check Lock File
        run: |
          poetry lock --check

      - name: Install Dependencies
        run: |
          poetry install --no-interaction --no-ansi

      - name: Lint
        run: |
          make lint

      - name: Unit Tests
        run: |
          make test-unit

      - name: Integration Tests
        run: |
          make pre-integration
          make test-integration
          make post-integration

      - name: Code Coverage
        id: coverage
        run: |
          poetry run coverage json
          COVERAGE=$(jq -r '.totals.percent_covered_display' coverage.json)
          echo $COVERAGE
          echo "COVERAGE=$COVERAGE" >> "$GITHUB_OUTPUT"

  docker:
    name: Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Container Image
        run: |
          docker buildx build .

  dependabot-automerge:
    name: Dependabot Auto Merge
    needs: [test, docker]
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && ( github.head_ref || github.ref_name ) != 'main' }}
    steps:
      - name: Fetch Dependabot Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve Dependabot PR
        run: gh pr review --approve "$PR_URL"
        if: ${{ (steps.metadata.outputs.package-ecosystem == 'pip' && steps.metadata.outputs.update-type != 'version-update:semver-major') || steps.metadata.outputs.package-ecosystem != 'pip' }}
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Dependabot PR
        if: ${{ (steps.metadata.outputs.package-ecosystem == 'pip' && steps.metadata.outputs.update-type != 'version-update:semver-major') || steps.metadata.outputs.package-ecosystem != 'pip' }}
        run: gh pr merge --auto --squash "$PR_URL" || echo "Merge conflict caused failure, waiting for dependabot to rebase"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  coverage-badge:
      name: Coverage Badge
      if: github.ref == 'refs/heads/main'
      needs: [test]
      runs-on: ubuntu-latest
      env:
        COVERAGE: ${{ needs.test.outputs.coverage }}

      steps:
        - uses: actions/checkout@v4
          name: Checkout Wiki
          with:
            repository: ${{ github.repository }}.wiki
            path: coverage

        - name: Generate Coverage Badge
          working-directory: coverage
          run: |
            npx badge-maker "coverage" "${{ env.COVERAGE }}%" ":brightgreen" > "coverage.svg"

        - name: Commit Coverage Badge to Wiki
          working-directory: coverage
          run: |
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add coverage.svg
            git diff --staged --quiet || git commit -m "Update code coverage"
            git push
